sonar.projectKey=mgupta83_sample-app-pg
sonar.organization=mgupta83
sonar.sources=packages
sonar.tests=packages
sonar.test.inclusions=**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/deploy/**,**/coverage/**
